stages:
  - build
  - deploy

variables:
  IMAGE_NAME: adarshmali/fooderpfrontend
  IMAGE_TAG: $CI_COMMIT_SHA
  KUBE_DEPLOYMENT: fooderpfrontend

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - kubectl set image deployment/$KUBE_DEPLOYMENT fooderpfrontend=$IMAGE_NAME:$IMAGE_TAG
    - kubectl rollout status deployment/$KUBE_DEPLOYMENT
